services:
  backend:
    build: 
      context: ./backend
    container_name: hoard_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://hoard_user:hoard_password@db:5432/hoard_db
    depends_on:
      - db
    networks:
      - hoard_network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:15
    container_name: hoard_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hoard_user
      POSTGRES_PASSWORD: hoard_password
      POSTGRES_DB: hoard_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hoard_network

  nginx:
    image: nginx:latest
    container_name: hoard_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - hoard_network

  frontend:
    build:
      context: ./frontend
    container_name: hoard_frontend
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - hoard_network
    command: sh -c "npm install && npm run dev"

networks:
  hoard_network:
    driver: bridge

volumes:
  pgdata: