services:
  app:
    build: 
      context: .
    container_name: hoard_app
    restart: always
    ports:
      - "3000:3000"  # frontend用
      - "4000:4000"  # backend用
    environment:
      - DATABASE_URL=postgres://hoard_user:hoard_password@db:5432/hoard_db
    depends_on:
      - db
    networks:
      - hoard_network
    volumes:
      - ./src:/app
      - /app/backend/node_modules
      - /app/frontend/node_modules
    command: /bin/sh -c "cd /app/frontend && npm run dev & cd /app/backend && npm run dev"

  db:
    image: postgres:15
    container_name: hoard_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hoard_user
      POSTGRES_PASSWORD: hoard_password
      POSTGRES_DB: hoard_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hoard_network

  nginx:
    image: nginx:latest
    container_name: hoard_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - hoard_network

networks:
  hoard_network:
    driver: bridge

volumes:
  pgdata: